-- 006a — make the logistics/insurance tables part of the versioned migration set.
--
-- ROOT CAUSE (cross-environment schema drift, found by the clean-rebuild probe):
-- carriers, freight_quotes, bills_of_lading, customs_entries,
-- certificates_of_origin, carbon_footprints, insurance_policies and
-- insurance_claims have Sequelize models but were NEVER created by a migration —
-- they only came into existence via dev-only `sequelize.sync()` (index.js, gated
-- on DB_SYNC!='false' && env!='production'). Migration 007 then ALTERs
-- freight_quotes et al to add RLS. Result:
--   • dev (sync ON):  tables exist before 007 → boot works.
--   • prod (sync OFF): tables never created → 007 fails with
--     'relation "trade.freight_quotes" does not exist' → service cannot boot on
--     a fresh database.
-- This migration closes that gap so the migration set is self-contained and a
-- pure `node migrate.js` rebuild succeeds in every environment.
--
-- RUNNER COMPATIBILITY: flat CREATE TABLE IF NOT EXISTS statements only — no
-- DO-blocks, no CREATE TYPE (native pg enums are not re-creatable idempotently
-- without a DO-block, and would break dev DBs where sync() already made them).
-- The model-level ENUMs are expressed here as VARCHAR + CHECK over the identical
-- value domain — same data, same validation, same app behaviour (Sequelize
-- exchanges plain strings on the wire). IF NOT EXISTS makes this a safe no-op on
-- every DB that already has these tables (dev, and any sync-bootstrapped env).
-- The DDL mirrors exactly what sequelize.sync() emits for these models.

CREATE TABLE IF NOT EXISTS "trade"."carriers" ("id" VARCHAR(64), "name" VARCHAR(255) NOT NULL, "rating" DECIMAL(3,2) DEFAULT 4.5, "regions" JSONB DEFAULT '[]', "avg_delivery_time" VARCHAR(50), "starting_price" DECIMAL(20,2) DEFAULT 0, "logo" TEXT, "description" TEXT, "specializations" JSONB DEFAULT '[]', "modes" JSONB DEFAULT '[]', "base_fee" DECIMAL(20,2) DEFAULT 0, "rate_per_kg" DECIMAL(20,4) DEFAULT 0, "transit_days" INTEGER DEFAULT 21, "reliability" INTEGER DEFAULT 90, "active" BOOLEAN DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."freight_quotes" ("id" VARCHAR(80), "tenant_id" TEXT, "order_id" TEXT, "carrier_id" VARCHAR(64), "carrier_name" VARCHAR(255), "mode" VARCHAR(20), "price" DECIMAL(20,2), "currency" VARCHAR(10) DEFAULT 'USD', "estimated_days" INTEGER, "reliability" INTEGER, "status" VARCHAR(20) DEFAULT 'quoted' CHECK ("status" IN ('quoted','selected','expired','booked')), "valid_until" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."bills_of_lading" ("id" VARCHAR(64), "tenant_id" TEXT, "shipment_id" TEXT, "order_id" TEXT, "bl_number" VARCHAR(80) UNIQUE, "bl_type" VARCHAR(20) DEFAULT 'negotiable' CHECK ("bl_type" IN ('negotiable','straight','seaway')), "shipper" JSONB DEFAULT '{}', "consignee" JSONB DEFAULT '{}', "notify_party" JSONB DEFAULT '{}', "carrier_id" VARCHAR(64), "carrier_name" VARCHAR(255), "vessel_name" VARCHAR(255), "voyage_number" VARCHAR(80), "port_of_loading" VARCHAR(255), "port_of_discharge" VARCHAR(255), "place_of_receipt" VARCHAR(255), "place_of_delivery" VARCHAR(255), "goods_description" TEXT, "packages" INTEGER, "gross_weight" DECIMAL(20,3), "measurement" VARCHAR(80), "freight_terms" VARCHAR(20) DEFAULT 'prepaid' CHECK ("freight_terms" IN ('prepaid','collect')), "status" VARCHAR(20) DEFAULT 'draft' CHECK ("status" IN ('draft','issued','transferred','surrendered','released','cancelled')), "current_holder" VARCHAR(160), "holder_history" JSONB DEFAULT '[]', "signatures" JSONB DEFAULT '[]', "issued_at" TIMESTAMP WITH TIME ZONE, "surrendered_at" TIMESTAMP WITH TIME ZONE, "released_at" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."customs_entries" ("id" VARCHAR(64), "tenant_id" TEXT, "shipment_id" TEXT, "order_id" TEXT, "origin_country" VARCHAR(80), "destination_country" VARCHAR(80), "entry_type" VARCHAR(20) DEFAULT 'import', "declarant" JSONB DEFAULT '{}', "importer" JSONB DEFAULT '{}', "exporter" JSONB DEFAULT '{}', "incoterm" VARCHAR(10), "currency" VARCHAR(10) DEFAULT 'USD', "customs_value" DECIMAL(20,2) DEFAULT 0, "line_items" JSONB DEFAULT '[]', "total_duty" DECIMAL(20,2) DEFAULT 0, "total_tax" DECIMAL(20,2) DEFAULT 0, "total_payable" DECIMAL(20,2) DEFAULT 0, "status" VARCHAR(40) DEFAULT 'draft', "template" VARCHAR(40), "filing_reference" VARCHAR(80), "authorized_by" VARCHAR(120), "inspection_notes" TEXT, "submitted_at" TIMESTAMP WITH TIME ZONE, "cleared_at" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."certificates_of_origin" ("id" VARCHAR(64), "tenant_id" TEXT, "shipment_id" TEXT, "order_id" TEXT, "customs_entry_id" TEXT, "certificate_number" VARCHAR(80) UNIQUE, "coo_type" VARCHAR(20) DEFAULT 'non_preferential' CHECK ("coo_type" IN ('non_preferential','preferential')), "agreement" VARCHAR(80), "exporter" JSONB DEFAULT '{}', "consignee" JSONB DEFAULT '{}', "producer" JSONB DEFAULT '{}', "origin_country" VARCHAR(80), "destination_country" VARCHAR(80), "goods" JSONB DEFAULT '[]', "origin_criterion" VARCHAR(40) DEFAULT 'WO', "transport_details" VARCHAR(255), "status" VARCHAR(20) DEFAULT 'draft' CHECK ("status" IN ('draft','issued','submitted','certified','rejected')), "chamber" VARCHAR(160), "e_stamp" JSONB DEFAULT NULL, "certifier_stamp" JSONB DEFAULT NULL, "issued_at" TIMESTAMP WITH TIME ZONE, "certified_at" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."carbon_footprints" ("id" VARCHAR(64), "tenant_id" TEXT, "shipment_id" TEXT, "order_id" TEXT, "mode" VARCHAR(20), "distance_km" DECIMAL(20,2), "weight_kg" DECIMAL(20,2), "weight_tonnes" DECIMAL(20,4), "emission_factor" DECIMAL(10,2), "co2_kg" DECIMAL(20,2), "co2_tonnes" DECIMAL(20,4), "offset_cost_usd" DECIMAL(20,2), "offset_status" VARCHAR(20) DEFAULT 'none' CHECK ("offset_status" IN ('none','pending','purchased')), "offset_provider" VARCHAR(120), "offset_reference" VARCHAR(120), "offset_purchased_at" TIMESTAMP WITH TIME ZONE, "methodology" VARCHAR(160), "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."insurance_policies" ("id" VARCHAR(64), "tenant_id" TEXT, "shipment_id" TEXT, "order_id" TEXT, "policy_number" VARCHAR(80) UNIQUE, "insurance_type" VARCHAR(20) DEFAULT 'cargo', "status" VARCHAR(20) DEFAULT 'pending', "insured" JSONB DEFAULT '{}', "beneficiary" JSONB DEFAULT '{}', "provider" VARCHAR(120), "coverage_amount" DECIMAL(20,2) DEFAULT 0, "currency" VARCHAR(10) DEFAULT 'USD', "premium" DECIMAL(20,2) DEFAULT 0, "premium_rate" DECIMAL(10,5), "deductible" DECIMAL(20,2) DEFAULT 0, "coverage_terms" JSONB DEFAULT '{}', "parametric_trigger" JSONB DEFAULT NULL, "premium_payment_ref" VARCHAR(120), "start_date" TIMESTAMP WITH TIME ZONE, "end_date" TIMESTAMP WITH TIME ZONE, "bound_at" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "trade"."insurance_claims" ("id" VARCHAR(64), "tenant_id" TEXT, "policy_id" VARCHAR(64), "shipment_id" TEXT, "claim_number" VARCHAR(80) UNIQUE, "amount" DECIMAL(20,2) DEFAULT 0, "status" VARCHAR(20) DEFAULT 'filed', "reason" TEXT, "assessor" VARCHAR(120), "payout_amount" DECIMAL(20,2), "payout_ref" VARCHAR(120), "filed_at" TIMESTAMP WITH TIME ZONE, "resolved_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "metadata" JSONB DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
